.TH DPASTE 1 2017-06-26

.SH NAME
.B dpaste
- A simple pastebin for light values (max 64KB) using OpenDHT distributed hash
table.

.SH SYNOPSIS
.B dpaste [-h]

.B dpaste [-v]

.B dpaste [-g \fIcode\fP]

.B dpaste [-e \fIcode\fP] [-s]

.SH DESCRIPTION

By default, \fBdpaste\fP will read its standard input for a file to paste on
OpenDHT.  For fetching a file, you have to provide the \fIcode\fP associated to
it using the flag \fB-g\fP. Then, \fBdpaste\fP will

.SH OPTIONS

.TP
\fB-h\fP
Prints some help.

.TP
\fB-v\fP
Shows the version of the program.

.TP
\fB-g\fP \fIcode\fP
Specifies the code \fIcode\fP used to recover the file on the DHT.

.TP
\fB-e\fP \fIrecipient\fP
Specifies wether the message should be encrypted using the OpenPGP protocol. If
so, \fIrecipient\fP is the recipient to encrypt message to. This can be any
string that GPG will correctly parse (fingerprint, email, ...).

.TP
\fB-s\fP
Tells wether message should be signed using the user's GPG key. The key has to
be configured through the configuration file (\fB$XDG_CONFIG_DIR/dpaste.conf\fP).

.SH RETURN CODE
The program returns 0 on success. Otherwise 1 is returned.

.SH FILES

.TP
\fB$XDG_CONFIG_DIR/dpaste.conf\fP
Main configuration file where. \fBdpaste\fP will look for this file to recover
complementary information.

.SH AUTHORS
\(bu
.\}
Simon Désaulniers <sim.desaulniers@gmail.com>

\(bu
.\}
Adrien Béraud <adrien.beraud@savoirfairelinux.com>
